### ISSUE TITLE
app crashes on 2nd upload attempt to get fit

### ISSUE THREAD

**Issue by srmadden** [CSAIL-LivingLab/getfit#1] opened 2015-01-24 02:47 UTC
manually uploading two activities to get fit results in a crash after the 2nd attempt

**Comment by RogerTangos** [comment] 2015-01-24 08:55
I'm not able to replicate this on the simulator or on my phone. The initial 15 second pause you reported in the other thread was a fail safe - If the app can't post within 15 seconds (for network connectivity reasons, or otherwise), it closes the modal window.

Are you able to log into getfit-d7-dev.mit.edu/dashboard, and post minute there? I suspect that the issue is that you're not a registered user... so there should probably be another try catch statement handling _that_ edge.

**Comment by RogerTangos** [comment] 2015-01-24 19:08
I've confirmed that this is happening only when users don't have getfit accounts that are able to post.

Options:
1) Fail gracefully, prompting the user to sign up for getfit
2) Do 1, and then disable posting to getfit. Disabling getfit posting would prevent the user from going to the getfit page, so the app would have no way of knowing if they'd signed up for getfit later.

Thoughts, @srmadden ?

**Comment by RogerTangos** [comment] 2015-01-26 20:38
Closed in f3397313efaa4fd93879a3a477239a7191276d60.

Disable getfit posting is requested in #6

**Closed as completed by RogerTangos** 2015-01-26 20:38 UTC
Labels: bug
